### ISSUE TITLE
App doesn't work.

### ISSUE THREAD

**Issue by ghost** [invoice-x/invoicex-gui#8]
Sorry for non descriptive title but the app doesn't work for anything other than the invoices included in tests, crashing for one pdf because you forgot to decrypt the pdf's. 

Looks like you built this app for passing the tests, instead of the other way round.

**Comment by duskybomb** [comment]
Which OS did you check it on? Can you run the app through terminal and share the error?

**Comment by ghost** [comment]
I did run it from a terminal (Is there any other way?). This is the error I got:

    /mnt/DATA/src/invoicex-gui                                                                                                                                                                        
    [22:09:07  master*]                                                                                                                                                                         
    > python main.py                                                                                                                                                                                  
    qt5ct: using qt5ct plugin                                                                                                                                                                         
    qt5ct: D-Bus global menu: no                                                                                                                                                                      
    PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will be corrected. [pdf.py:1736]                                                                                              
    Traceback (most recent call last):                                                                                                                                                                
      File "/mnt/DATA/src/invoicex-gui/invoicex/invoicex.py", line 302, in show_file_dialog                                                                                                           
        self.load_pdf_file()                                                                                                                                                                          
      File "/mnt/DATA/src/invoicex-gui/invoicex/invoicex.py", line 306, in load_pdf_file                                                                                                              
        if self.check_xml_for_pdf() is None:                                                                                                                                                          
      File "/mnt/DATA/src/invoicex-gui/invoicex/invoicex.py", line 408, in check_xml_for_pdf                                                                                                          
        pdf_root = pdf.trailer['/Root']                                                                                                                                                               
      File "/home/saga/.local/lib/python3.7/site-packages/PyPDF2/generic.py", line 516, in __getitem__                                                                                               
        return dict.__getitem__(self, key).getObject()
      File "/home/saga/.local/lib/python3.7/site-packages/PyPDF2/generic.py", line 178, in getObject
        return self.pdf.getObject(self).getObject()
      File "/home/saga/.local/lib/python3.7/site-packages/PyPDF2/pdf.py", line 1617, in getObject
        raise utils.PdfReadError("file has not been decrypted")
    PyPDF2.utils.PdfReadError: file has not been decrypted
    [1]    9009 abort (core dumped)  python main.py
    

All you need to do is prompt the user for password and decrypt the pdf like this:

    if input.isEncrypted:
        input.decrypt(pass)

You could try decrypting with an empty password(`pass` set to `""`) at first and prompt the user only if the `decrypt` call returns `0`

Please let me know if you need any more info.

**Comment by m3nu** [comment]
There was never support for encrypted pdfs and no plan to add it.
